apiVersion: apps/v1
kind: Deployment
metadata:
  name: space-3d-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: space-3d-site
  template:
    metadata:
      labels:
        app: space-3d-site
    spec:
      containers:
      - name: space-3d-site
        image: vishnukbhasker/space-3d-site:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
