apiVersion: v1
kind: Service
metadata:
  name: space-3d-service
spec:
  type: NodePort
  selector:
    app: space-3d-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
